CREATE TABLE `Product` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Nom` VARCHAR(255) NOT NULL,
	`Prix` FLOAT NOT NULL,
	`Description` VARCHAR(255) NOT NULL,
	`Famille` VARCHAR(255) NOT NULL,
	`Reference` VARCHAR(255) NOT NULL,
	`DateValid` DATE NOT NULL,
	`Image` VARCHAR(255),
	PRIMARY KEY (`ID`)
);
